19:17:44.604  [lettuce-nioEventLoop-18-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [101.34.208.43:6379]: Network is unreachable: no further information: /101.34.208.43:6379
io.netty.channel.AbstractChannel$AnnotatedSocketException: Network is unreachable: no further information: /101.34.208.43:6379
Caused by: java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_333]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716) ~[?:1.8.0_333]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_333]
19:17:55.815  [lettuce-nioEventLoop-18-1] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [101.34.208.43:6379]: Network is unreachable: no further information: /101.34.208.43:6379
io.netty.channel.AbstractChannel$AnnotatedSocketException: Network is unreachable: no further information: /101.34.208.43:6379
Caused by: java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_333]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716) ~[?:1.8.0_333]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_333]
19:18:19.525  [lettuce-nioEventLoop-18-5] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [101.34.208.43:6379]: connection timed out: /101.34.208.43:6379
19:18:33.721  [lettuce-nioEventLoop-18-6] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [101.34.208.43:6379]: connection timed out: /101.34.208.43:6379
19:18:46.566  [lettuce-nioEventLoop-18-7] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [101.34.208.43:6379]: Software caused connection abort: no further information: /101.34.208.43:6379
io.netty.channel.AbstractChannel$AnnotatedSocketException: Software caused connection abort: no further information: /101.34.208.43:6379
Caused by: java.net.SocketException: Software caused connection abort: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_333]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716) ~[?:1.8.0_333]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_333]
19:19:13.022  [lettuce-nioEventLoop-18-8] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [101.34.208.43:6379]: connection timed out: /101.34.208.43:6379
22:16:03.204  [http-nio-8089-exec-6] WARN  com.aliyun.oss - [Unknown]Unable to execute HTTP request: Connection pool shut down
22:16:47.465  [http-nio-8089-exec-7] WARN  com.aliyun.oss - [Unknown]Unable to execute HTTP request: Connection pool shut down
22:18:54.229  [http-nio-8089-exec-3] WARN  com.aliyun.oss - [Unknown]Unable to execute HTTP request: Connection pool shut down
22:27:55.554  [http-nio-8089-exec-4] WARN  com.aliyun.oss - [Unknown]Unable to execute HTTP request: Connection pool shut down
